name: management-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docke r
      - POSTGRES_DB=management
