export const jsonData = {
  draw: 0,
  recordsTotal: 5,
  recordsFiltered: 5,
  data: [
    [
      1,
      'Nome da Company',
      2024,
      '123456',
      'Portugal',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: true,
        },
        api_version: 1,
        resource: 1,
        download_url: null,
      },
    ],
    [
      2,
      'Nome da Company',
      2024,
      '12345435',
      'Modelo de texto',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: true,
        },
        api_version: 1,
        resource: 2,
        download_url: null,
      },
    ],
    [
      3,
      'Nome da Company',
      2024,
      '45345312',
      'Contratos',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: false,
        },
        api_version: 1,
        resource: 3,
        download_url: null,
      },
    ],
    [
      4,
      'Nome da Company',
      2024,
      '345453435',
      'Lisboa',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: true,
        },
        api_version: 1,
        resource: 4,
        download_url: null,
      },
    ],
    [
      5,
      'Nome da Company',
      2024,
      '345345345',
      'Albufeira',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: false,
        },
        api_version: 1,
        resource: 5,
        download_url: null,
      },
    ],
  ],
  columns: [
    {
      name: 'id',
      order: false,
      search: false,
      column_type: 'integer',
    },
    {
      name: 'company',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'reference_year',
      order: true,
      search: true,
      column_type: 'integer',
    },
    {
      name: 'budget_entity_code',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'budget_entity_name',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'budget_entity_type',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'state',
      order: false,
      search: false,
      column_type: 'string',
    },
    {
      name: 'action',
      order: false,
      search: false,
      column_type: 'actions',
    },
  ],
};
