export const jsonData = {
  draw: 0,
  recordsTotal: 678,
  recordsFiltered: 678,
  data: [
    [
      319,
      'Luságua Serviços',
      2024,
      '420733205',
      'APS -Porto de Sines',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: true,
        },
        api_version: 1,
        resource: 319,
        download_url: null,
      },
    ],
    [
      238,
      'Luságua Serviços',
      2024,
      '420711004',
      'Laboratório Albergaria - Operacional',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: true,
        },
        api_version: 1,
        resource: 238,
        download_url: null,
      },
    ],
    [
      290,
      'Luságua Serviços',
      2024,
      '420732000',
      'Gestão de Contratos - Centro',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: false,
        },
        api_version: 1,
        resource: 290,
        download_url: null,
      },
    ],
    [
      203,
      'Luságua Serviços',
      2024,
      '42004380',
      'GP - Arguo',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: true,
        },
        api_version: 1,
        resource: 203,
        download_url: null,
      },
    ],
    [
      234,
      'Luságua Serviços',
      2024,
      '420711000',
      'Laboratório Albergaria',
      'Centro de Custo',
      'copied_preclosure',
      {
        link_action: {
          show: true,
          update: false,
        },
        api_version: 1,
        resource: 234,
        download_url: null,
      },
    ],
  ],
  columns: [
    {
      name: 'id',
      order: false,
      search: false,
      column_type: 'integer',
    },
    {
      name: 'company',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'reference_year',
      order: true,
      search: true,
      column_type: 'integer',
    },
    {
      name: 'budget_entity_code',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'budget_entity_name',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'budget_entity_type',
      order: true,
      search: true,
      column_type: 'string',
    },
    {
      name: 'state',
      order: false,
      search: false,
      column_type: 'string',
    },
    {
      name: 'action',
      order: false,
      search: false,
      column_type: 'actions',
    },
  ],
};
